[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm', 'openssl']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = [
  'cd examples/nestjs && pnpm prisma generate',
  'cd examples/nestjs && pnpm run build',
]

[start]
cmd = "cd examples/nestjs && pnpm prisma migrate deploy && pnpm run start:prod"
